# Emulate a user configuring the module.
configfile: workflow.source_path("./test_config.yaml")


module grid_builder:
    pathvars:
        resources="resources/grid-builder",
        logs="logs/grid-builder",
    snakefile:
        "../../workflow/Snakefile"
    config:
        config["grid_builder"]


use rule * from grid_builder as grid_builder_*


rule all:
    default_target: True
    input:
        rules.grid_builder_retrieve_osm_all.input,
