%YAML 1.1
---
# yaml-language-server: $schema=./config.schema.json
countries:
- BE

retrieve:
  source: geofabrik
  force_redownload: false
  include_relations: true
  target_date:
  overpass_api:
    url: "https://overpass-api.de/api/interpreter"
    max_tries: 5
    timeout: 600
    user_agent:
      project_name: "grid-builder"
      email: ""
      website: "https://github.com/pypsa/grid-builder"

network:
  minimum_voltage_kv: 220.0
  frequency_hz:
    AC: 50.0
    DC: 0.0
  station_merge_radius_m: 500.0
  remove_under_construction: true
  remove_after: 2026-12-31

regions: {}

crs:
  geo: "EPSG:4326"
  distance: "EPSG:3035"
