countries:
  - benin
  - togo

retrieve:
  source: geofabrik
  primary_name: power
  features:
    - substation
    - line
  force_redownload: false
  mp: true
  stream_backend: true
  cache_primary: false
  target_date: null
